services:
  web:
    build: 
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8001 finalproject.asgi:application
    environment:
      - POSTGRES_HOST=db 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
      - redis
    volumes:
      - '.:/code'
      - '.:/workspace'
      
    stdin_open: true   
    tty: true    
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"

    
    restart: always