services:
  web:
    build: 
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - '.:/code'
      - '.:/workspace'
      
    stdin_open: true   
    tty: true    
    restart: unless-stopped
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"

    
    restart: always